language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

script:
  - go build .

before_install:
  - go get github.com/mitchellh/gox

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Yim5sVP798jUKq/HoS4OBsIYdmdvubgy1DgUS6soDNnP5GuMRbPh3vXjmmyuJvEA/dLotcLsrBzgVDTF8JvouE89d29bKghFpVEa34F8iJZVzuykxS3rKrho9s5/NFdxv7thvoExaEd1mxkYa5idxN4yL84fh6n9YucmL9LbXz1yDsv6J0SmkUdbh6takvTYIEoT9qmxT5YhKnLoRLeMKgiixXIgy1opdUk1MSzEH1H15+hBMbIfTQ+1m/4bq2lAYLhvvGdSpcpSjWRheSsdsjyYJyEMxvw2NGzMRv3fj3IdHY0SWiLKXDeMP8UBcoYHs5z84x+41qMrVBP+MG+UxaDU29q5r62A0xci4L2jkpTdmsd9pQk1MlZlOJQ2iJZbY0fLEi2SttG06wfHjgnrNyIQWoxikiZkcCcJD2Ug0mVix2Bd/lYkKweGuUq2yIgWu8AYr6eQfOjh5PJ7/QVmwgdlLL7ZWLx2jluasY6JlpPOYKyssA1i/fYtCmFIW9zUQ8cBBFFP+4mfQOaHGQUK8RToKpCnBk2nNGkAnYq50qhC1geuKAkiE5VQIq7qNijRgXGr8oQ8LYSmjLyPZPHWacCqaXrYvR0NusGuA8IigIJ8CZXeDqpOZiMFdytGn9OVItA+SVQu2ZtCHSII5l+IEcPpaAkEi6aBMwCIbo4Sa+I=
  file_glob: true
  file: dist/**/*
  on:
    repo: MichaelMure/mdr
    go: 1.12
    tags: true
